### ISSUE TITLE
Content MIssing

### ISSUE THREAD

**Issue by EverNife** [MeSoLost/MeSoLost-in-Space-modpack#1]
I cant see the content :V

**Comment by MeSoLost** [comment]
I had planned on using this to host the pack for technic but I ended up using dropbox instead.  Would you want to see all the config files from the server here??  I could potentially put up everything except some stuff from commandhelper I made for the server.  (security -_- )  You'd have the jar and could see what's under the hood sort of speak.  There wouldn't be much "code" I could really share but there's a few things I could.  Would be method script from commandhelper though.

**Comment by EverNife** [comment]
Sure i would like to see ^^

**Comment by MeSoLost** [comment]
alrighty, be patient and everything that I can legally put here I will so all the base server files and configs.  What will not be here are the plugin jars and mod files (rehosting perms), player data, plugins configs that have database access, command helper scripts which are the glue of the server (security reasons), map files and backups (size of files).  I wrote it on my master to-do list so it'll happen. (9 items as of this moment now)

**Comment by MeSoLost** [comment]
There's some content to hold you over. You can get the mods by downloading the pack and you'll need to find the thermos libraries zip download (too big to upload here) and you should be able to make a working server.  However, I did not include any of my commandhelper scripts. =\  Security n all -_- you understand.  There's some important stuff in them and make up the core of my server.  There's other plugins out there that can replace what I've put together there so it's not entirely vital for you to make a server.
